pipeline{
	
		agent {
			label 'Slave5_Induccion'
		}
	
        
		triggers {
        	pollSCM('@hourly')
		}
	
		tools {
			jdk 'JDK8_Centos' 
			gradle 'Gradle5.0_Centos' 
		}
	
		options {
			buildDiscarder(logRotator(numToKeepStr: '5'))
			disableConcurrentBuilds()
		}
		
		environment {
        PROJECT_PATH_BACK = 'parqueadero'
		}
		parameters{
			booleanParam defaultValue: false, description: 'Push a registry AWS', name: 'pushdeploy'
		}
		
		stages{
		
			stage('Checkout') {
				steps {
                	echo '------------>Checkout - Git parqueadero<------------'
                	checkout([$class: 'GitSCM', branches: [[name: '${BRANCH_NAME}']], 
                	doGenerateSubmoduleConfigurations: false, 
                	extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'parqueadero']], 
                	gitTool: 'Git_Centos', submoduleCfg: [], 
                	userRemoteConfigs: [[credentialsId: 'GitHub_chuchodavidgomez', url: 'https://github.com/chuchodavidgomez/estacionamiento_adn_ceiba']]])
				}
			}
		
		
		
			stage('Checkout-comun') {
				steps {
                	echo '------------>Checkout - Git Comun<------------'

                	checkout([$class: 'GitSCM', branches: [[name: 'master']], 
                	doGenerateSubmoduleConfigurations: false, 
                	extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'Comun']], 
                	gitTool: 'Git_Centos', submoduleCfg: [], 
                	userRemoteConfigs: [[credentialsId: 'GitHub_chuchodavidgomez', url: 'https://github.com/chuchodavidgomez/estacionamiento_adn_ceiba']]])
				}
			}
		
			stage('Build') {//listo
				steps{
					echo "------------>Build<------------"
					sh 'gradle --b ./build.gradle build -x test'
				}
			}
			
			stage('Unit Test'){//listo
				steps{
					echo "------------>Unit Tests<------------"
					sh 'gradle --b ./build.gradle test'
				}
			}
			
			stage('Sonar Analysis'){//listo
				steps{
					echo '------------>Analisis de codigo estatico<------------'
					  withSonarQubeEnv('Sonar') {
					  	sh "${tool name: 'SonarScanner',type:'hudson.plugins.sonar.SonarRunnerInstallation'}/bin/sonar-scanner"
					  }
				}
			}
				
		}
		post {
			failure {
				echo "----------fallo-----------"
				mail(to: 'jesus.gomez@ceiba.com.co',
				subject: "fallo Pipeline:${currentBuild.fullDisplayName}",
				body:"Build failed in Jenkins: Project: ${env.JOB_NAME} Build /n Number: ${env.BUILD_NUMBER} URL de build: ${env.BUILD_NUMBER}/n/nPlease go to ${env.BUILD_URL} and verify the build")				
			}
			
			success {
				echo 'This will run only if successful'
				junit '**/build/test-results/test/*.xml'
			}
		}	
			
}